---
- hosts: all
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Cleaning up after ourselves to remove packages we have installed
      yum: pkg={{ item }} state=absent
      with_items:
        - telnet
        - lynx
        - httpd
        - apache2
      ignore_errors: yes
