---
- hosts: apacheweb
  user: test
  sudo: yes
  gather_facts: no
  tasks:
    - include: plays/pkgs.yml
    - name: Verification task
      raw: yum list installed | grep telnet >> /home/test/pkgs.log
      
  
