---
- hosts: all
  user: test
  sudo: yes
  gather_facts: no
  tasks:
    - name: System uptime
      raw: uptime >> /home/test/uptime.log
    - name: List directory /var
      raw: ls -l /var >> /home/test/dir.list
      run_once: yes 
