---
- hosts: all
  user: test
  sudo: yes
  gather_facts: no
  tasks:
    - name: Install telnet
      yum: pkg={{ item }} state=latest
      with_items:
        - telnet
        - lynx
      tags:
        - packages
    - name: Verificationt task
      raw: yum list installed | grep telnet > /home/test/pkgs.log
      tags: 
        - logging
    
