---
- hosts: apacheweb
  user: test
  sudo: yes
  gather_facts: no
  tasks:
    - name: Install apache
      yum: pkg=httpd state=latest
    - name: Verify systemctl
      shell: systemctl status httpd
      register: result
      until: result.stdout.find("active (running)") != -1
      retries: 5
      delay: 5
    - debug: var=result 
