---
- name: Install/update IBM Installation Manager
  command:
    chdir={{ tmp_dir }}
    {{ tmp_dir }}/groupinstc -log {{ tmp_dir }}/logs/im_install.{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}.log -acceptLicense -sVP -dL {{ agent_data_location }} -installationDirectory {{ iim_install_location }}
  register: cout
  changed_when: (cout.stdout.find('Installed com.ibm.cic.agent') != -1) or (cout.stdout.find('Updated to com.ibm.cic.agent') != -1)
- debug: var=cout.stdout.find('Installed com.ibm.cic.agent')
